CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA,
       A.NOME AS ALUNO,
       AO.SEMESTRE,
       O.HORARIO_INICIAL,
       O.HORARIO_FINAL,
       O.DIA_SEMANA,
       P.NOME AS PROFESSOR,
       D.NOME_DISCIPLINA
FROM ALUNOS_OFERTAS AO
INNER JOIN ALUNOS A
    ON AO.MATRICULA = A.MATRICULA
INNER JOIN OFERTAS O
    ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
    ON O.MATRICULA = P.MATRICULA
INNER JOIN DISCIPLINAS D
    ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;