CREATE TABLE ALUNOS_OFERTAS(
	MATRICULA	NUMERIC	NOT NULL,
	CODIGO_OFERTA	NUMERIC	NOT NULL,
	LIMITE_ALUNOS	NUMERIC	NOT NULL,
	SEMESTRE	VARCHAR(6)	NOT NULL,
	DATA_INICIAL	DATE NOT NULL,
	DATA_FINAL	DATE 	NOT NULL
);SSSS