--INDEX---
CREATE INDEX ALUNOS_NOME_IDX ON ALUNOS(NOME);
CREATE INDEX OFERTAS_DIA_IDX ON OFERTAS (DIA_SEMANA);
CREATE INDEX DISCIPLINA_NOME_IDX ON DISCIPLINAS(NOME_DISCIPLINA);
CREATE INDEX PROFESSORES_NOME_IDX ON PROFESSORES(NOME);

---SEQUENCES---
CREATE SEQUENCE DISCIPLINAS_SEQ;
CREATE SEQUENCE OFERTAS_SEQ;

--ADICIONANDO COLUNAS---
ALTER TABLE ALUNOS ADD (EMAIL VARCHAR(200)NULL, CPF VARCHAR(200)NULL);
ALTER TABLE PROFESSORES ADD(CONTATO VARCHAR(200)NULL);
ALTER TABLE OFERTAS ADD(DATA_CRIACAO DATE NULL);

--MODIFICANDO COLUNAS---
ALTER TABLE ALUNOS MODIFY(EMAIL VARCHAR2(250));
ALTER TABLE OFERTAS MODIFY(DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL);

---RENOMEAR COLUNAS---
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME TO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;
ALTER TABLE PROFESSORES RENAME COLUMN NOME TO NOME_PROFESSOR;
ALTER TABLE DISCIPLINAS  RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNOS_OFERTAS  RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;

--RENOMEAR TABELAS--
ALTER TABLE TELEFONES RENAME TO TELEFONES_ALUNOS;

--REMOVER COLUNAS---
ALTER TABLE PROFESSORES DROP COLUMN CONTATO;
ALTER TABLE ALUNOS  DROP COLUMN EMAIL;
ALTER TABLE ALUNOS DROP COLUMN CPF;

--ADICIONANDO AS CHAVES PRIMÁRIAS---
ALTER TABLE TELEFONES_ALUNOS ADD PRIMARY KEY(TELEFONE);
ALTER TABLE ALUNOS ADD PRIMARY KEY(MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS  ADD PRIMARY KEY(MATRICULA_ALUNO);
ALTER TABLE OFERTAS ADD PRIMARY KEY(CODIGO_OFERTA);
ALTER TABLE PROFESSORES  ADD PRIMARY KEY(MATRICULA_PROFESSOR);
ALTER TABLE DISCIPLINAS  ADD PRIMARY KEY(CODIGO_DISCIPLINA);

ALTER TABLE TELEFONES_ALUNOS RENAME COLUMN MATRICULA_ALUNOS TO MATRICULA_ALUNO;

--ADICIONAR CHAVES ESTRANGEIRAS----
ALTER TABLE TELEFONES_ALUNOS 
ADD CONSTRAINT TELEFONE_ALUNO_FK 
	FOREIGN KEY (MATRICULA_ALUNO)
	REFERENCES ALUNOS(MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS
	ADD CONSTRAINT ALUNOS_ALUNO_FK
	FOREIGN KEY(CODIGO_OFERTA)
	REFERENCES ALUNOS(MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS 
	ADD CONSTRAINT ALUNOS_OFERTA_FK
	FOREIGN KEY(CODIGO_OFERTA)
	REFERENCES OFERTAS(CODIGO_OFERTA);

ALTER TABLE OFERTAS
	ADD CONSTRAINT OFERTAS_PROFESSOR_FK
	FOREIGN KEY(MATRICULA_PROFESSOR)
	REFERENCES PROFESSORES(MATRICULA_PROFESSOR);

ALTER TABLE OFERTAS
	ADD CONSTRAINT OFERTAS_DISCIPLINAS_FK
	FOREIGN KEY(CODIGO_DISCIPLINA)
	REFERENCES DISCIPLINAS(CODIGO_DISCIPLINA);

ALTER TABLE DISCIPLINAS 
	ADD CONSTRAINT DISCIPLINAS_DEPENDENCIA_FK
	FOREIGN KEY(CODIGO_DISCIPLINA_DEPENDENCIA)
	REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);
