CREATE TABLE DISCIPLINAS(
	CODIGO_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR(100)	NOT NULL,
	CARGA_HORARIA	NUMERIC(3)	NOT NULL,
	EMENTA	VARCHAR(4000)	NOT NULL,
	CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC 


);