UPDATE ALUNOS
   SET DATA_NASCIMENTO = TO_DATE('29/04/2011', 'DD/MM/YYYY')
 WHERE MATRICULA_ALUNO = 40004;

UPDATE PROFESSORES
   SET FORMACAO = 'PHD'
 WHERE FORMACAO = 'DOUTORADO';


UPDATE PROFESSORES
   SET FORMACAO = 'MSC'
 WHERE MATRICULA_PROFESSOR IN (55126, 55133);


UPDATE DISCIPLINAS
   SET CODIGO_DISCIPLINA_DEPENDENCIA = 31313
 WHERE NOME_DISCIPLINA = 'MACHINE LEARNING';

UPDATE OFERTAS
   SET MATRICULA_PROFESSOR = 55128
 WHERE CODIGO_DISCIPLINA = 12345
   AND MATRICULA_PROFESSOR = 55125;


UPDATE ALUNOS_OFERTAS
   SET LIMITE_ALUNOS = 70
 WHERE CODIGO_OFERTA IN (SELECT O.CODIGO_OFERTA
                           FROM OFERTAS O
                          INNER JOIN DISCIPLINAS D
                             ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA
                          WHERE D.NOME_DISCIPLINA = 'NATURAL LANGUAGE PROCESSING');


COMMIT;

