
UPDATE DISCIPLINAS
   SET CODIGO_DISCIPLINA_DEPENDENCIA = NULL
 WHERE CODIGO_DISCIPLINA_DEPENDENCIA IN (85853, 75189);

DELETE FROM DISCIPLINAS
 WHERE CODIGO_DISCIPLINA IN (85853, 75189);



DELETE FROM OFERTAS
 WHERE CODIGO_OFERTA = 1742;

DELETE FROM PROFESSORES P
 WHERE NOT EXISTS (SELECT 1
                     FROM OFERTAS O
                    WHERE O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR);

DELETE FROM TELEFONES_ALUNOS
 WHERE TELEFONE LIKE '27%';

-- Desfaz alterações
ROLLBACK;

