

DROP SEQUENCE DISCIPLINAS_SEQ;
DROP SEQUENCE OFERTAS_SEQ;


DROP VIEW ALUNOS_MATRICULADOS;
DROP VIEW DISCIPLINAS_PROFESSOR;

DROP TABLE ALUNOS_OFERTAS;
DROP TABLE OFERTAS;
DROP TABLE DISCIPLINAS;
DROP TABLE TELEFONES_ALUNOS; 
DROP TABLE TELEFONES;
DROP TABLE ALUNOS;
DROP TABLE PROFESSORES;

/*CRIANDO TABELA*/
CREATE TABLE TELEFONES(
    TELEFONE VARCHAR2(11) NOT NULL,
    MATRICULA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS(
    MATRICULA NUMERIC NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE PROFESSORES(
    MATRICULA NUMERIC(5) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    FORMACAO VARCHAR2(100) NOT NULL
);

CREATE TABLE DISCIPLINAS(
    CODIGO_DISCIPLINA NUMERIC NOT NULL,
    NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
    CARGA_HORARIA NUMERIC(3) NOT NULL,
    EMENTA VARCHAR2(4000) NOT NULL,
    CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC
);

CREATE TABLE OFERTAS(
    CODIGO_OFERTA NUMERIC NOT NULL,
    HORARIO_INICIAL TIMESTAMP NOT NULL,
    HORARIO_FINAL TIMESTAMP NOT NULL,
    DIA_SEMANA VARCHAR2(20) NOT NULL,
    MATRICULA NUMERIC(5) NOT NULL,
    CODIGO_DISCIPLINA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS_OFERTAS(
    MATRICULA NUMERIC NOT NULL,
    CODIGO_OFERTA NUMERIC NOT NULL,
    LIMITE_ALUNOS NUMERIC NOT NULL,
    SEMESTRE VARCHAR(6) NOT NULL,
    DATA_INICIAL DATE NOT NULL,
    DATA_FINAL DATE NOT NULL
);

/*  CRIANDO INDEXES */
CREATE INDEX ALUNOS_NOME_IDX ON ALUNOS(NOME);
CREATE INDEX OFERTAS_DIA_IDX ON OFERTAS(DIA_SEMANA);
CREATE INDEX DISCIPLINA_NOME_IDX ON DISCIPLINAS(NOME_DISCIPLINA);
CREATE INDEX PROFESSORES_NOME_IDX ON PROFESSORES(NOME);

/* CRIANDO SEQUENCES */
CREATE SEQUENCE DISCIPLINAS_SEQ;
CREATE SEQUENCE OFERTAS_SEQ;



/* ADICIONANDO COLUNA*/
ALTER TABLE ALUNOS ADD (EMAIL VARCHAR2(200) NULL, CPF VARCHAR2(11) NULL);
ALTER TABLE PROFESSORES ADD (CONTATO VARCHAR2(200) NULL);
ALTER TABLE OFERTAS ADD (DATA_CRIACAO DATE NULL);

/*MODIFICANDO COLUNA*/
ALTER TABLE ALUNOS MODIFY (EMAIL VARCHAR2(250));
ALTER TABLE OFERTAS MODIFY (DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL);

/* RENOMEA A COLUNA */
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME TO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;
ALTER TABLE PROFESSORES RENAME COLUMN NOME TO NOME_PROFESSOR;
ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNOS_OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;

/* RENOMEIA TABELA */
ALTER TABLE TELEFONES RENAME TO TELEFONES_ALUNOS;

/* EXCLUI COLUNA */
ALTER TABLE PROFESSORES DROP COLUMN CONTATO;
ALTER TABLE ALUNOS DROP COLUMN EMAIL;
ALTER TABLE ALUNOS DROP COLUMN CPF;


ALTER TABLE TELEFONES_ALUNOS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;

/* ADICIONANDO CHAVE PRIMARIA*/
ALTER TABLE TELEFONES_ALUNOS ADD PRIMARY KEY(TELEFONE);
ALTER TABLE ALUNOS ADD PRIMARY KEY(MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS ADD PRIMARY KEY(MATRICULA_ALUNO, CODIGO_OFERTA);
ALTER TABLE OFERTAS ADD PRIMARY KEY(CODIGO_OFERTA);
ALTER TABLE PROFESSORES ADD PRIMARY KEY(MATRICULA_PROFESSOR);
ALTER TABLE DISCIPLINAS ADD PRIMARY KEY(CODIGO_DISCIPLINA);

/*ADICIONANDO AS FOREIGN KEY*/
ALTER TABLE TELEFONES_ALUNOS 
	ADD CONSTRAINT TELEFONE_ALUNO_FK 
	FOREIGN KEY (MATRICULA_ALUNO)
	REFERENCES ALUNOS(MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS
	ADD CONSTRAINT ALUNOS_ALUNO_FK
	FOREIGN KEY(MATRICULA_ALUNO)
	REFERENCES ALUNOS(MATRICULA_ALUNO);

ALTER TABLE ALUNOS_OFERTAS 
	ADD CONSTRAINT ALUNOS_OFERTA_FK
	FOREIGN KEY(CODIGO_OFERTA)
	REFERENCES OFERTAS(CODIGO_OFERTA);

ALTER TABLE OFERTAS
	ADD CONSTRAINT OFERTAS_PROFESSOR_FK
	FOREIGN KEY(MATRICULA_PROFESSOR)
	REFERENCES PROFESSORES(MATRICULA_PROFESSOR);

ALTER TABLE OFERTAS
	ADD CONSTRAINT OFERTAS_DISCIPLINAS_FK
	FOREIGN KEY(CODIGO_DISCIPLINA)
	REFERENCES DISCIPLINAS(CODIGO_DISCIPLINA);

ALTER TABLE DISCIPLINAS 
	ADD CONSTRAINT DISCIPLINAS_DEPENDENCIA_FK
	FOREIGN KEY(CODIGO_DISCIPLINA_DEPENDENCIA)
	REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);



/* CRIANDO VIEWS*/

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNO,
       A.NOME_ALUNO AS ALUNO,
       AO.SEMESTRE,
       O.HORARIO_INICIAL,
       O.HORARIO_FINAL,
       O.DIA_SEMANA,
       P.NOME_PROFESSOR AS PROFESSOR,
       D.NOME_DISCIPLINA
FROM ALUNOS_OFERTAS AO
INNER JOIN ALUNOS A
    ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
    ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
    ON O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR
INNER JOIN DISCIPLINAS D
    ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROFESSOR AS PROFESSOR
     , P.FORMACAO
     , D.CODIGO_DISCIPLINA
     , D.NOME_DISCIPLINA
     , D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
    ON O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR
INNER JOIN DISCIPLINAS D
    ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

/*INSERINDO DADOS */
INSERT ALL
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40001, 'JOÃO GABRIEL', TO_DATE('02/04/1985', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40002, 'JOÃO JOSÉ', TO_DATE('31/12/2001', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40003, 'JOSÉ GABRIEL', TO_DATE('04/07/1999', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40004, 'ANTONIO JOSÉ', TO_DATE('27/09/1998', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40005, 'ANTONIO MARCIO', TO_DATE('20/04/1955', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40006, 'JOSÉ ANTÔNIO', TO_DATE('29/04/1955', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40007, 'MARCIO ANTONIO', TO_DATE('14/03/1967', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40008, 'JOÃO ANTONIO', TO_DATE('21/02/2002', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40009, 'MARCIO GABRIEL', TO_DATE('08/06/2009', 'DD/MM/YYYY'))
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO) VALUES (40010, 'GABRIEL ANTONIO', TO_DATE('01/01/1970', 'DD/MM/YYYY'))
SELECT * FROM DUAL;

INSERT ALL
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('11990897030', 40001)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('27990897031', 40001)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('33990897032', 40002)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('22990897033', 40010)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('27990897034', 40003)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('22990897035', 40006)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('11990897036', 40008)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('14990897037', 40003)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('18990897038', 40004)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('79990897039', 40007)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('83990897040', 40005)
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO) VALUES ('81990897041', 40009)
SELECT * FROM DUAL;

INSERT ALL
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55124, 'CARLOS ANTONIO', 'MESTRADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55125, 'PAULO ANTONIO', 'DOUTORADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55126, 'PATRICIA CARMEN', 'ESPECIALIZAÇÃO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55127, 'ALINE SANTOS', 'MESTRADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55128, 'ALICE DE SOUZA', 'MESTRADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55129, 'LUIZ CARLOS', 'DOUTORADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55130, 'LUCAS PEDRO', 'DOUTORADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55131, 'PEDRO HENRIQUE', 'MESTRADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55132, 'MARIA OLGA', 'DOUTORADO')
    INTO PROFESSORES (MATRICULA_PROFESSOR, NOME_PROFESSOR, FORMACAO) VALUES (55133, 'CAMILA PEREZ', 'ESPECIALIZAÇÃO')
SELECT * FROM DUAL;

INSERT ALL
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (48851, 'DATA SCIENCE', 80, 'EMENTA DA DISCIPLINA DATA SCIENCE', 75189)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (45812, 'DATA ANALYTICS', 40, 'EMENTA DA DISCIPLINA DATA ANALYTICS', NULL)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (33412, 'MACHINE LEARNING', 80, 'EMENTA DA DISCIPLINA MACHINE LEARNING', NULL)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (12345, 'NATURAL LANGUAGE PROCESSING', 80, 'EMENTA DA DISCIPLINA NATURAL LANGUAGE PROCESSING', 33412)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (55213, 'COMPUTER VISION', 80, 'EMENTA DA DISCIPLINA COMPUTER VISION', 33412)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (18493, 'ROBOTIC', 60, 'EMENTA DA DISCIPLINA ROBOTIC', 31313)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (13131, 'DATABASE', 60, 'EMENTA DA DISCIPLINA DATABASE', 31313)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (31313, 'COMPUTER PROGRAMMING', 30, 'EMENTA DA DISCIPLINA COMPUTER PROGRAMMING', NULL)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (85853, 'BIG DATA', 75, 'EMENTA DA DISCIPLINA BIG DATA', 75189)
    INTO DISCIPLINAS (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA) VALUES (75189, 'DATA MINING', 80, 'EMENTA DA DISCIPLINA DATA MINING', NULL)
SELECT * FROM DUAL;

INSERT ALL
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1418, TO_TIMESTAMP('1900-01-01 18:45:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'SEGUNDA', 55125, 33412)
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1519, TO_TIMESTAMP('1900-01-01 20:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'SEGUNDA', 55131, 12345)
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1742, TO_TIMESTAMP('1900-01-01 18:45:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 20:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'TERÇA', 55125, 48851)
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1112, TO_TIMESTAMP('1900-01-01 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 23:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'QUARTA', 55126, 55213)
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1313, TO_TIMESTAMP('1900-01-01 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 21:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'QUARTA', 55130, 13131)
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1632, TO_TIMESTAMP('1900-01-01 18:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'SEXTA', 55125, 12345)
    INTO OFERTAS (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROFESSOR, CODIGO_DISCIPLINA) VALUES (1674, TO_TIMESTAMP('1900-01-01 19:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('1900-01-01 21:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'QUINTA', 55133, 55213)
SELECT * FROM DUAL;

INSERT ALL
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40001, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40001, 1519, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40001, 1313, 35, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40002, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40002, 1632, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40003, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40003, 1519, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40004, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40004, 1313, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40005, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40006, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40006, 1674, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40006, 1519, 35, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40007, 1674, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40007, 1313, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40008, 1313, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40008, 1519, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40009, 1674, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
    INTO ALUNOS_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL) VALUES (40010, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))
SELECT * FROM DUAL;

COMMIT;
