CREATE TABLE OFERTAS(
	CODIGO_DISCIPLINA	NUMERIC	NOT NULL,
	NOME_DISCIPLINA	VARCHAR(100)	NOT NULL,
	CARGA_HORARIA 	NUMERIC(3)	NOT NULL,
	EMENTA	VARCHAR(4000)	NOT NULL,
	CODIGO_DISCPLINA_DEPENDENCIA NUMERIC
);