/*DROP TABLES*/
DROP TABLE ALUNOS_OFERTAS;
DROP TABLE OFERTAS;
DROP TABLE DISCIPLINAS;
DROP TABLE TELEFONES;
DROP TABLE ALUNOS;
DROP TABLE PROFESSORES;

/*CREATE TABLES*/
CREATE TABLE TELEFONES(
    TELEFONE VARCHAR2(11) NOT NULL,
    MATRICULA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS(
    MATRICULA NUMERIC NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE PROFESSORES(
    MATRICULA NUMERIC(5) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    FORMACAO VARCHAR2(100) NOT NULL
);

CREATE TABLE DISCIPLINAS(
    CODIGO_DISCIPLINA NUMERIC NOT NULL,
    NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
    CARGA_HORARIA NUMERIC(3) NOT NULL,
    EMENTA VARCHAR2(4000) NOT NULL,
    CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC
);

CREATE TABLE OFERTAS(
    CODIGO_OFERTA NUMERIC NOT NULL,
    HORARIO_INICIAL TIMESTAMP NOT NULL,
    HORARIO_FINAL TIMESTAMP NOT NULL,
    DIA_SEMANA VARCHAR2(20) NOT NULL,
    MATRICULA NUMERIC(5) NOT NULL,
    CODIGO_DISCIPLINA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS_OFERTAS(
    MATRICULA NUMERIC NOT NULL,
    CODIGO_OFERTA NUMERIC NOT NULL,
    LIMITE_ALUNOS NUMERIC NOT NULL,
    SEMESTRE VARCHAR2(10),
    DATA_INICIAL DATE NOT NULL,
    DATA_FINAL DATE NOT NULL
);