CREATE VIEW DISCIPLINAS_PROFESSORES AS
SELECT P.NOME AS PROFESSOR
     , P.FORMACAO
     , D.CODIGO_DISCIPLINA
     , D.NOME_DISCIPLINA
     , D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
    ON O.MATRICULA = P.MATRICULA
INNER JOIN DISCIPLINAS D
    ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;


);